-- creates a function SafeDiv
DELIMITER //
CREATE FUNCTION SafeDiv(a INT, b INT)
RETURNS DECIMAL
BEGIN
	IF b = 0 THEN
		RETURN CAST(0 AS DECIMAL);
	ELSE
		RETURN CAST(a / b AS DECIMAL);
	END IF;
END;
//
DELIMITER ;
